image: k33g/capsule:0.0.1

tasks:
  - name: initialize
    before: |
      CAPSULE_VERSION="v0.2.8"
      wget -O - https://raw.githubusercontent.com/bots-garden/capsule/${CAPSULE_VERSION}/install-capsule-launcher.sh| bash
    init: |
      echo "🚀 ..."
      cd functions/hello
      ./refresh-package.sh
      ./build.sh
      cd ../functions/hey
      ./refresh-package.sh
      ./build.sh
      cd ../functions/hola
      ./refresh-package.sh
      ./build.sh

ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
    - PKief.material-icon-theme
